# Generated by Django 4.1.7 on 2023-04-26 20:22

import BackEnd.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(upload_to=BackEnd.models.unique_agent_image_id)),
            ],
        ),
    ]
