# Generated by Django 4.1.7 on 2023-05-14 04:31

import BackEnd.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='', max_length=50)),
                ('house_number', models.CharField(default='', max_length=100)),
                ('postal_code', models.PositiveIntegerField(default=0, validators=[BackEnd.models.my_postal_code_validator])),
                ('locality', models.TextField(default='', max_length=20)),
                ('method', models.CharField(default='', max_length=10)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('cover_photo', models.ImageField(default='', upload_to='Cover_Images')),
                ('house_type', models.TextField(default='', max_length=20)),
                ('beds', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('baths', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('total_rooms', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('basement_sq_ft', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('garage_sq_ft', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('total_house_sq_ft', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('total_apartment_sq_ft', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('lot_size_sq_ft', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('year_biult', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(default='')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='BuyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Posted_Images')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BackEnd.buy')),
            ],
        ),
    ]
