# Generated by Django 4.1.7 on 2023-05-14 05:04

import BackEnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_buy_buyimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='cover_photo',
            field=models.ImageField(default='', upload_to=BackEnd.models.unique_cover_image_id),
        ),
        migrations.AlterField(
            model_name='buyimages',
            name='image',
            field=models.ImageField(upload_to=BackEnd.models.unique_images_id),
        ),
    ]
