# Generated by Django 4.1.7 on 2023-05-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_alter_buy_cover_photo_alter_buyimages_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='basement_sq_ft',
            new_name='basement_meter_square',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='beds',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='garage_sq_ft',
            new_name='garage_meter_square',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='lot_size_sq_ft',
            new_name='total_apartment_meter_square',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='total_apartment_sq_ft',
            new_name='total_house_meter_square',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='total_house_sq_ft',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='total_rooms',
        ),
    ]
