# Generated by Django 4.1.7 on 2023-05-16 05:19

import BackEnd.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0005_alter_buy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(default='', max_length=50)),
                ('house_number', models.CharField(default='', max_length=100)),
                ('postal_code', models.PositiveIntegerField(default=0, validators=[BackEnd.models.my_postal_code_validator])),
                ('locality', models.TextField(default='', max_length=20)),
                ('method', models.CharField(default='', max_length=10)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('cover_photo', models.ImageField(default='', upload_to=BackEnd.models.unique_cover_image_id)),
                ('house_type', models.TextField(blank=True, default='', max_length=20, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('baths', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('garage_meter_square', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('total_house_meter_square', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('total_apartment_meter_square', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('year_biult', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(default='')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='RentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=BackEnd.models.unique_images_id)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='BackEnd.rent')),
            ],
        ),
    ]
