# Generated by Django 4.1.7 on 2023-05-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_rent_rentimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='floor_no',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
