# Generated by Django 4.1.7 on 2023-05-18 14:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0007_rent_floor_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None)),
                ('email', models.EmailField(default='', max_length=100)),
            ],
        ),
    ]
