# Generated by Django 4.1.7 on 2023-05-25 14:41

import BackEnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0008_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=BackEnd.models.front_page)),
            ],
        ),
    ]
